name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install .NET 7
        run: |
          wget -q https://dot.net/v1/dotnet-install.sh
          bash dotnet-install.sh -c Current
      - name: Install Dependencies
        run: |
          cd src
          dotnet restore
      - name: Build
        run: |
          cd src
          dotnet build --configuration Release
      - name: Test
        run: |
          cd src
          dotnet test --logger "trx;LogFileName=testresults.trx"

      - name: Set Status
        run: echo "::set-output name=status::${{ job.status }}"
